### ISSUE TITLE
Add a testing pipeline for contributors

### ISSUE THREAD

**Issue by jeFF0Falltrades** [jeFF0Falltrades/rat_king_parser#17]
RKP is missing one key component today: Testing.

My plan is to develop a testing suite for contributors to run, and part of that plan is to include a standard set of samples to run against.

I'm still brainstorming ideas for how to best execute this as I don't want to host malicious files within the repo, and I don't want them to be downloaded alongside the package when `pip` is used.

Instead, I'm considering the following options:

* Host them separately and include a helper script for contributors to safely download them from a trusted centralized location when they want to test.
* Use mock data derived from the real samples to test (safer, but makes it harder to troubleshoot file parsing errors)

I will update this Issue when I've thought some more on this and have fleshed out a testing pipeline.

**Comment by doomedraven** [comment]
something like this

```
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout test files repo
        uses: actions/checkout@v4
        with:
          repository: CAPESandbox/CAPE-TestFiles
          path: tests/data/

      - uses: ./.github/actions/python-setup/
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Ruff
        run: poetry run ruff check . --line-length 132 --ignore E501,E402

      - name: See if any parser changed
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'cape_parsers/CAPE/core/*.py'
              - 'cape_parsers/CAPE/community/**.py'

      - name: Test parsers only if any parser changed
        if: steps.changes.outputs.src == 'true'
        run: |
          sudo apt install yara
          poetry run pip install yara-python
          poetry run python -m pytest tests_parsers -s --import-mode=append
```

i do run path filter to not run test on not related files, but you cna remove it
